package com.alang.dto.chat;

import lombok.Data;
import java.time.LocalDateTime;

/**
 * A condensed summary of a conversation segment.
 *
 * ARCHITECTURAL RATIONALE:
 * - Represents 5-10 message exchanges condensed into 1-2 paragraphs
 * - Used to provide context to LLM without replaying full history
 * - Generated by LLMService after certain thresholds (e.g., every 10 messages)
 */
@Data
public class ConversationSummaryDto {
    private String summaryId;
    private String language;

    /**
     * Condensed summary text.
     * Example: "User explored particle usage in Japanese. Discussed は、が、を、に
     * with multiple examples. User struggled with を vs に distinction."
     */
    private String summaryText;

    /**
     * Key topics covered (for quick reference)
     */
    private String[] topics;

    /**
     * When this summary was created
     */
    private LocalDateTime createdAt;

    /**
     * How many actual messages this summary represents
     */
    private int messageCount;
}
